services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tms
      TZ: Africa/Harare
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d:ro


  config-server:
    build: ./config-server
    container_name: config-server
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/config
      TZ: Africa/Harare
      JAVA_TOOL_OPTIONS: -Duser.timezone=Africa/Harare
    volumes:
      - ./config:/config:ro
    ports:
      - "8888:8888"
    depends_on:
      - mysql

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    restart: unless-stopped
    environment:
      TZ: Africa/Harare
      JAVA_TOOL_OPTIONS: -Duser.timezone=Africa/Harare
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8761/eureka
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka
      TZ: Africa/Harare
      JAVA_TOOL_OPTIONS: -Duser.timezone=Africa/Harare
    ports:
      - "8082:8082"
    volumes:
      - ./uploads:/uploads/monitor
    depends_on:
      - mysql
      - eureka-server
      - config-server

  transformer-service:
    build: ./transformer-service
    container_name: transformer-service
    restart: unless-stopped
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8761/eureka
      LORIOT_WS_URL: ${LORIOT_WS_URL}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka
      TZ: Africa/Harare
      JAVA_TOOL_OPTIONS: -Duser.timezone=Africa/Harare
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
      - config-server

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: unless-stopped
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8761/eureka
      SERVER_PORT: 8085
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888/
      TZ: Africa/Harare
      JAVA_TOOL_OPTIONS: -Duser.timezone=Africa/Harare
    depends_on:
      - mysql
      - eureka-server
      - config-server
    ports:
      - "8085:8085"
    
  gateway:
    build: ./gateway
    container_name: api-gateway
    restart: unless-stopped
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8761/eureka
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka
      TZ: Africa/Harare
      JAVA_TOOL_OPTIONS: -Duser.timezone=Africa/Harare
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server

volumes:
  mysql_data: